# Site settings
title: Evenly
description: > # this means to ignore newlines until "baseurl:"
  Evenly is a software engineering consultancy for mobile software based in Berlin, Germany. We build high quality mobile apps for iOS and Android.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://evenly.io" # the base hostname & protocol for your site
twitter_username: evenly_io
github_username:  evenlyio
facebook_page_id: "1474156202844845"

exclude: 
    - Gemfile
    - Gemfile.lock
    - README.md
    - Rakefile
    - .gitlab-ci.yml

# Contact details
company_name: Evenly GmbH
address: Oranienstraße 6
zip: 10997
city: Berlin
phone: +49 30 60984272
email: hello@evenly.io


# Build settings
markdown: kramdown

collections:
  jobs:
    permalink: /jobs/:path/
    output: true
  projects:
    permalink: /projects/:path/
    output: true
